```Instagram Influencer Model Prediction```

* This project focuses on building and evaluating machine learning models to predict influencer performance based on key social media metrics. The dataset contains important features such as followers, posts, average likes, engagement rate, total likes, country, and joining date, which are used to predict the target variable (Influence Score / Ranking).

* The project began with data preprocessing and feature engineering, including handling missing values, converting textual numerical formats (k, m, b) into standardized numeric values, encoding categorical variables, and transforming date features into meaningful time-based attributes.

* After data preparation, the dataset was split into training and testing sets. Multiple machine learning algorithms were implemented to compare performance, including regression models. Model evaluation was conducted using appropriate performance metrics such as R² score, Mean Absolute Error (MAE), and Root Mean Squared Error (RMSE).

* The objective of this project is to identify the most significant factors influencing influencer performance and to develop a predictive model capable of estimating influence score based on engagement and follower-related metrics.

* Overall, this project demonstrates practical application of data preprocessing, feature engineering, model building, and performance evaluation techniques in a real-world social media analytics context.

In [25]:
# import required library
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# import scikit learn library 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score

### 01 import dataset

In [3]:
# Now import the data set which already cleand in previous EDA Analysis
df = pd.read_csv("C:\\Users\\mohdy\\OneDrive\\Desktop\\intern project\\top_insta_infl_cleaned_data.csv")

In [9]:
# copy dataset 
data = df.copy()

In [10]:
# print 
data.head()

   rank channel_info  influence_score  ... joining_month_name  like_follower_ratio  post_follower_ratio
0     1    instagram               50  ...           February             3.896848             0.000012
1     2    cristiano               61  ...                May            51.940299             0.000006
2     3     leomessi               47  ...               June            19.295499             0.000003
3     4  selenagomez               40  ...               July            32.120482             0.000005
4     5  kyliejenner               42  ...           November           156.240409             0.000019

[5 rows x 15 columns]

In [12]:
data.columns

Index(['rank', 'channel_info', 'influence_score', 'influence_category',
       'posts', 'followers', 'avg_likes', 'engagement_rate',
       'new_post_avg_like', 'total_likes', 'country', 'joining_year',
       'joining_month_name', 'like_follower_ratio', 'post_follower_ratio'],
      dtype='object')

### 02 Feature selection

In [13]:
# Feature selection
X = data[['followers', 'avg_likes', 'engagement_rate', 'new_post_avg_like', 'like_follower_ratio', 'post_follower_ratio']]
y = data['influence_score']

### 03 Train_Test_Split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=52)

### 04 Standardize features

In [19]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

### 05 Model Apply

In [22]:
# Apply linear Regression model 
rf = RandomForestRegressor(n_estimators=30)
rf.fit(x_train, y_train)

# This is for Score
rf.score(x_test, y_test)*100 , rf.score(x_train, y_train)*100

(96.20278367718447, 97.38165599135068)

### 06 Model Predictions and evaluation

In [26]:
y_pred = rf.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 170.1235
R^2 Score: -0.29037848907766994

In [27]:
# Display actual vs predicted values for the first 10 samples
comparison = pd.DataFrame({'Actual': y_test.values.flatten(), 'Predicted': y_pred.flatten()})
comparison.head(10)

   Actual  Predicted
0       7   6.233333
1      18   6.300000
2       9   6.233333
3       6   6.233333
4       7   3.200000
5      14   6.233333
6       4   6.233333
7       4   3.200000
8       5   3.200000
9       8   3.200000

``` Conclusion ```

* In this project, machine learning models were successfully implemented to predict influencer performance based on engagement metrics, follower count, and content activity. After preprocessing and feature engineering, multiple regression models were trained and evaluated to identify the most effective predictive approach.

* The results indicate that engagement-related features such as average likes and engagement rate play a significant role in predicting influence score, while posting frequency has relatively lower predictive impact. The selected model demonstrated strong predictive capability based on evaluation metrics such as

* ```R² score  -0.29037```

* ``` RMSE  170.1235```.

* Overall, this project highlights that influencer performance can be effectively estimated using data-driven techniques. It also demonstrates the importance of engagement quality over mere content quantity in determining digital influence.